---
# Pfade auf dem Host-System
vaultwarden_compose_dir: "/opt/vaultwarden"
vaultwarden_compose_file: "docker-compose.yaml"
vaultwarden_data_dir: "/srv/service_data/vw"

# Traefik / Netzwerk Einstellungen
vaultwarden_public_url: "{{ sops.vaultwarden.domain }}"
vaultwarden_traefik_enable: true
vaultwarden_traefik_router_name: "vaultwarden"
vaultwarden_traefik_cert_resolver: "{{ sops.proxy.cert_resolver | default('dnshetzner', true) }}"
vaultwarden_traefik_network: "{{ sops.proxy.network_name | default('traefik-net', true) }}"
