---
# Pfade auf dem Host-System
vaultwarden_compose_dir: "/opt/vaultwarden"
vaultwarden_compose_file: "{{ default_compose_file }}"
vaultwarden_data_dir: "/srv/service_data/vw"

# Traefik / Netzwerk Einstellungen
vaultwarden_public_url: "{{ sops.vaultwarden.domain }}"
vaultwarden_traefik_enable: true
vaultwarden_traefik_router_name: "vaultwarden"
vaultwarden_traefik_cert_resolver: "{{ traefik_cert_resolver }}"
vaultwarden_traefik_network: "{{ traefik_network }}"
