---
ntfy_compose_dir: "/opt/ntfy"
ntfy_compose_file: "docker-compose.yaml"

ntfy_timezone: "Europe/Berlin"

ntfy_public_url: "ntfy.home.wbrck.de"
ntfy_traefik_enable: true
ntfy_traefik_router_name: "ntfy"
ntfy_traefik_cert_resolver: "{{ sops.proxy.cert_resolver | default('dnshetzner', true) }}"
ntfy_traefik_network: "{{ sops.proxy.network_name | default('traefik-net', true) }}"
