---
- name: Ensure Actual Budget directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  become: true
  loop:
    - "{{ actual_budget_compose_dir }}"
    - "{{ actual_budget_data_dir }}"
    - "{{ actual_budget_server_files_dir }}"
    - "{{ actual_budget_user_files_dir }}"

- name: Deploy Actual Budget Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ actual_budget_compose_dir }}/{{ actual_budget_compose_file }}"
    owner: root
    group: root
    mode: "0644"

- name: Pull images
  community.docker.docker_compose_v2_pull:
    project_src: "{{ actual_budget_compose_dir }}"

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ actual_budget_compose_dir }}"
  register: actual_budget_output

- name: Show results
  ansible.builtin.debug:
    var: actual_budget_output
    verbosity: 1
