---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name:
      - xorriso
      - gpg
      - curl
    state: present
  when: ansible_facts.os_family != "Darwin"

- name: Install dependencies (macOS)
  ansible.builtin.package:
    name:
      - xorriso
      - gnupg
      - curl
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: Create the temporary directory
  ansible.builtin.file:
    path: "{{ autoin_ubuntu_target_dir }}"
    state: directory
    mode: "0750"
