---
- name: Install dependencies
  become: true
  package:
    name:
      - xorriso
      - gpg
      - curl
    state: present
  # FIX: Use dictionary syntax
  when: ansible_facts['os_family'] != "Darwin"

- name: Install dependencies (macOS)
  package:
    name:
      - xorriso
      - gnupg
      - curl
    state: present
  # FIX: Use dictionary syntax
  when: ansible_facts['os_family'] == "Darwin"

- name: Create the temporary directory
  file:
    path: "{{ target_dir }}"
    state: directory
