---
- name: Configure the target system and install dependencies
  include_tasks: configure.yml

- name: Download and verify the ISO
  include_tasks: download_verify.yml

- name: Generate the ISO
  include_tasks: generate_iso.yml

