---
# Pfade auf dem Host-System
actual_budget_compose_dir: "{{ services_compose_base }}/actual_budget"
actual_budget_compose_file: "{{ default_compose_file }}"
actual_budget_data_dir: "{{ services_data_base }}/actual"
actual_budget_server_files_dir: "{{ actual_budget_data_dir }}/server-files"
actual_budget_user_files_dir: "{{ actual_budget_data_dir }}/user-files"

# Traefik / Netzwerk Einstellungen
actual_budget_public_url: "budget.home.wbrck.de"
actual_budget_traefik_enable: true
actual_budget_traefik_router_name: "actual"
actual_budget_traefik_cert_resolver: "{{ traefik_cert_resolver }}"
actual_budget_traefik_network: "{{ traefik_network }}"
