---
# Pfade auf dem Host-System
audiobookshelf_compose_dir: "{{ services_compose_base }}/audiobookshelf"
audiobookshelf_compose_file: "{{ default_compose_file }}"
audiobookshelf_data_dir: "{{ services_data_base }}/audiobookshelf"
audiobookshelf_audiobooks_dir: "{{ audiobookshelf_data_dir }}/audiobooks"
audiobookshelf_podcasts_dir: "{{ audiobookshelf_data_dir }}/podcasts"
audiobookshelf_config_dir: "{{ audiobookshelf_data_dir }}/config"
audiobookshelf_metadata_dir: "{{ audiobookshelf_data_dir }}/metadata"

# Zeitzone
audiobookshelf_timezone: "{{ default_timezone }}"

# Traefik / Netzwerk Einstellungen
audiobookshelf_public_url: "audio.home.wbrck.de"
audiobookshelf_traefik_enable: true
audiobookshelf_traefik_network: "{{ traefik_network }}"
audiobookshelf_traefik_router_name: "audiobookshelf"
audiobookshelf_traefik_cert_resolver: "{{ traefik_cert_resolver }}"
