---
# Pfade auf dem Host-System
freshrss_compose_dir: "{{ services_compose_base }}/freshrss"
freshrss_compose_file: "{{ default_compose_file }}"
freshrss_base_dir: "{{ services_data_base }}/freshrss"
freshrss_data_dir: "{{ freshrss_base_dir }}/data"
freshrss_extensions_dir: "{{ freshrss_base_dir }}/extensions"

# Zeitzone
freshrss_timezone: "{{ default_timezone }}"

# FreshRSS Einstellungen
freshrss_cron_min: "*/15"

# xExtension-Readable
freshrss_readable_extension_repo: "https://github.com/printfuck/xExtension-Readable.git"
freshrss_readable_extension_version: "HEAD"

# Traefik / Netzwerk Einstellungen
freshrss_public_url: "{{ sops.freshrss.domain }}"
freshrss_traefik_enable: true
freshrss_traefik_network: "{{ traefik_network }}"
freshrss_traefik_router_name: "freshrss"
freshrss_traefik_cert_resolver: "{{ traefik_cert_resolver }}"
