# Pfade auf dem Host-System
opencloud_compose_dir: "{{ services_compose_base }}/opencloud"
opencloud_compose_file: "{{ default_compose_file }}"
opencloud_config_dir: "{{ services_data_base }}/opencloud/config"
opencloud_data_dir: "{{ services_data_base }}/opencloud/data"

# Container Image
opencloud_image: "opencloudeu/opencloud-rolling"
opencloud_tag: "latest"
opencloud_uid_gid: "1000:1000"

# OpenCloud Einstellungen
opencloud_public_url: "{{ sops.opencloud.domain }}"
opencloud_admin_password: "{{ sops.opencloud.admin_password }}"

# Traefik / Netzwerk Einstellungen
opencloud_traefik_enable: true
opencloud_traefik_router_name: "opencloud"
opencloud_traefik_cert_resolver: "{{ traefik_cert_resolver }}"
opencloud_traefik_network: "{{ traefik_network }}"
